/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cargo.ui;

import com.cargo.storage.dao.ProductDAO;
import com.cargo.storage.model.Product;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yura
 */
public class AddProdToStore extends javax.swing.JFrame {

    /**
     * Creates new form AddProdToStore
     */
    ProductDAO proddao;
    List<Product> listProduct;
    workerFrame wf;
    int indexStore;
    public AddProdToStore(workerFrame wf, int indexStore) {
        this.wf = wf;
        this.indexStore = indexStore;
        try {
            initComponents();
            proddao = new ProductDAO();
            listProduct = proddao.listOfProduct();
            
            for (int i=0;i<listProduct.size(); i++){
            
                jcmbProd.addItem(listProduct.get(i).getName());
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddProdToStore.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AddProdToStore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcmbProd = new javax.swing.JComboBox<>();
        jbtnAdd = new javax.swing.JButton();
        jtfCount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtnAdd.setText("Добавить");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jtfCount.setText(" ");

        jLabel1.setText("Продукт:");

        jLabel2.setText("Количество:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 104, Short.MAX_VALUE))
                            .addComponent(jcmbProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
          try {
                int i = jcmbProd.getSelectedIndex();
                int indexForQ = listProduct.get(i).getId();
                int count = Integer.parseInt(jtfCount.getText().trim());
                proddao.addProdToStorehouse(indexForQ, indexStore, count);
                wf.refreshProdOnStoreView(indexStore);
                dispose();
                  } catch(NumberFormatException exc){         
                      JOptionPane.showMessageDialog(
                                    wf,
                                    "Ошибка: "
                                                    + exc.getMessage(), "Error",
                                    JOptionPane.ERROR_MESSAGE);

                  } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(
                                    wf,
                                    "Ошибка: "
                                                    + ex.getMessage(), "Error",
                                    JOptionPane.ERROR_MESSAGE);
                }
             
    }//GEN-LAST:event_jbtnAddActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JComboBox<String> jcmbProd;
    private javax.swing.JTextField jtfCount;
    // End of variables declaration//GEN-END:variables
}
