/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cargo.ui;

import com.cargo.report.describedoc;
import com.cargo.storage.dao.OrderDAO;
import com.cargo.storage.model.Order;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author yura
 */
public class FinishOrders extends javax.swing.JFrame {

    /**
     * Creates new form FinishOrders
     */
    
    OrderDAO orddao;
    logistFrame lf;
    List<Order> list;
       
    public FinishOrders() {
        try {
            //this.lf = lf;
            orddao = new OrderDAO();
            list = orddao.getFinishOrders();
            DefaultListModel<String> model = new DefaultListModel<>();
            initComponents();
            jListOrder.setModel(model);
            for(int i = 0; i< list.size(); i++){
            
                model.addElement(list.get(i).getName());
            
            }
            
       
        } catch (Exception ex) {
            Logger.getLogger(FinishOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListOrder = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jListOrder);

        jLabel1.setText("Выберите заказ:");

        jbtnAdd.setText("Выбрать заказ");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jbtnAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAdd)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            int index = jListOrder.getSelectedIndex();
            int idOrd = list.get(index).getIdOrder();
            describedoc dedoc = new describedoc(idOrd);
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Сохранение отчета.");
            if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
                 dedoc.create(fileChooser.getSelectedFile());
            }
            
               
            
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FinishOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdd;
    // End of variables declaration//GEN-END:variables
}
