/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cargo.ui;

import com.cargo.storage.dao.OrderDAO;
import com.cargo.storage.dao.ProductDAO;
import com.cargo.storage.dao.StorehouseDAO;
import com.cargo.storage.model.Location;
import com.cargo.storage.model.Order;
import com.cargo.storage.model.Path;
import com.cargo.storage.model.Point;
import com.cargo.storage.model.Product;
import com.cargo.storage.model.Products;
import com.cargo.storage.model.Storehouse;
import com.cargo.tablemodels.OrderTableModel;
import com.cargo.tablemodels.PathTableModel;
import com.cargo.tablemodels.ProductTableModel;
import com.cargo.tablemodels.ProductsOnOrderTableModel;
import com.cargo.tablemodels.ProductsOnStoreTableModel;
import com.cargo.tablemodels.StorehouseTableModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yura
 */
public class logistFrame extends javax.swing.JFrame  {

    /**
     * Creates new form userFrame
     */
    StorehouseTableModel model;
    ProductsOnStoreTableModel prodModel;
    ProductsOnOrderTableModel prodordModel;
    ProductTableModel productCatalog;
    PathTableModel pathModel;
    OrderTableModel ordModel;
    StorehouseDAO strhdao;
    OrderDAO orddao;
    ProductDAO proddao;
    List<Product> productsCatalog;
    Point pFrom;
    Point pTo;
    List<Path> path;
    public static String password = "123";
    
    public logistFrame() throws Exception {
        
        List<Storehouse> storehouses = null;
        List<Order> orders = null;
        
        proddao = new ProductDAO();
        productsCatalog = proddao.listOfProduct();
        
        strhdao = new StorehouseDAO();
        storehouses = strhdao.getAllStorehouses();        
        orddao = new OrderDAO();        
        orders = orddao.getAllOrders();
        
        this.ordModel = new OrderTableModel(orders);
	this.model = new StorehouseTableModel(storehouses);
        this.productCatalog = new ProductTableModel(productsCatalog);
        
        initComponents();
        
    }

    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbStore = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProdsOfOrder = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfState = new javax.swing.JTextField();
        jtfStore = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfFrom = new javax.swing.JTextField();
        jtfTo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePath = new javax.swing.JTable();
        jbtnChangeStatus = new javax.swing.JButton();
        jbtnChangePath = new javax.swing.JButton();
        jbtnTransport = new javax.swing.JButton();
        jbtnTime = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtbStore.setName(" "); // NOI18N

        jScrollPane4.setViewportView(jTableProdsOfOrder);

        jLabel5.setText("Состав заказа:");

        jTableOrder.setModel(ordModel);
        jScrollPane3.setViewportView(jTableOrder);

        jTableOrder.getSelectionModel().addListSelectionListener( new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try{
                    int row = jTableOrder.getSelectedRow();
                    int indexOrd = Integer.parseInt(ordModel.getValueAt(row, 0).toString());
                    //System.out.println(row);
                    List<Products> productsOfOrder = null;

                    String state = "";
                    String store = "";
                    productsOfOrder = orddao.getProductsOfOrder(indexOrd);
                    state = orddao.getState(indexOrd);
                    store = orddao.getStoreOnMoment(indexOrd);
                    pFrom = orddao.getFrom(indexOrd);
                    pTo = orddao.getTo(indexOrd);
                    path = orddao.getPath(indexOrd);
                    String from = pFrom.getStorehouse().getName();
                    String to = pTo.getStorehouse().getName();

                    pathModel = new PathTableModel(path);

                    prodordModel = new ProductsOnOrderTableModel(productsOfOrder);
                    jtfFrom.setText(from);
                    jtfTo.setText(to);
                    jtfState.setText(state);
                    jtfStore.setText(store);
                    jTablePath.setModel(pathModel);
                    jTableProdsOfOrder.setModel(prodordModel);
                    jbtnChangePath.setEnabled(true);
                    jbtnTime.setEnabled(true);
                    jbtnTransport.setEnabled(true);
                    jbtnChangeStatus.setEnabled(true);
                } catch(Exception e){}

            }

        } );

        jLabel4.setText("Заказы:");

        jLabel6.setText("Статус заказа:");

        jtfState.setEditable(false);
        jtfState.setText(" ");

        jtfStore.setEditable(false);
        jtfStore.setText(" ");

        jLabel7.setText("Склад:");

        jtfFrom.setEditable(false);
        jtfFrom.setText(" ");

        jtfTo.setEditable(false);
        jtfTo.setText(" ");

        jLabel9.setText("Откуда:");

        jLabel10.setText("Куда:");

        jLabel11.setText("Путь перемещения:");

        jScrollPane6.setViewportView(jTablePath);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnChangeStatus.setText("Изменить статус");
        jbtnChangeStatus.setEnabled(false);
        jbtnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeStatusActionPerformed(evt);
            }
        });

        jbtnChangePath.setText("Изменить маршрут");
        jbtnChangePath.setEnabled(false);
        jbtnChangePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangePathActionPerformed(evt);
            }
        });

        jbtnTransport.setText("Транспорт");
        jbtnTransport.setEnabled(false);
        jbtnTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransportActionPerformed(evt);
            }
        });

        jbtnTime.setText("Время");
        jbtnTime.setEnabled(false);
        jbtnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnChangeStatus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(378, 378, 378)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(jtfTo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnTransport, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtnTime, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jbtnChangePath)))
                                .addGap(97, 97, 97)))
                        .addComponent(jtfStore, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jbtnTransport))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jbtnTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jbtnChangeStatus))
                    .addComponent(jbtnChangePath))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jtbStore.addTab("Заказы", jPanel2);

        jMenu1.setText("Файл");

        jMenuSave.setText("Сохранить отчет");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Смена");

        jMenuItem1.setText("Сменить пользователя");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbStore)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbStore)
                .addContainerGap())
        );

        jtbStore.getAccessibleContext().setAccessibleName("tabStore");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            strhdao.closeConnection();
            orddao.closeConnection();
            proddao.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(logistFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jbtnChangePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangePathActionPerformed
        try {
            int row = jTableOrder.getSelectedRow();
            int indexOrd = Integer.parseInt(ordModel.getValueAt(row, 0).toString()); 
            int count = pathModel.getRowCount();
            String[] roleItems = strhdao.getRoles();
            ChangeRoute.createAndShowGUI(indexOrd, count, roleItems, this);
            // csp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(logistFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnChangePathActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            this.dispose();
            orddao.closeConnection();
            strhdao.closeConnection();
            proddao.closeConnection();
            
            Authorization auth = new Authorization(this, true);
            auth.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(logistFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    private void jbtnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeStatusActionPerformed
          try {          
            ChangeState cs = new ChangeState(this);
            cs.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(logistFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jbtnChangeStatusActionPerformed

    private void jbtnTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransportActionPerformed
       try{
        int row = jTablePath.getSelectedRow();
        int indexPath = Integer.parseInt(pathModel.getValueAt(row, 6).toString());
        
        ChangeTransport chtr = new ChangeTransport(indexPath, this);
        chtr.setVisible(true);
       } catch(Exception ex) {
       
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error",
					JOptionPane.ERROR_MESSAGE);
       
       }
    }//GEN-LAST:event_jbtnTransportActionPerformed

    private void jbtnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimeActionPerformed
        try{
        
            int row = jTablePath.getSelectedRow();
            int indexPath = Integer.parseInt(pathModel.getValueAt(row, 6).toString());
            ChangeTime chtime = new ChangeTime(this, indexPath);
            chtime.setVisible(true);
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error",
					JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnTimeActionPerformed

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        FinishOrders fo = new FinishOrders();
        fo.setVisible(true);
        
    }//GEN-LAST:event_jMenuSaveActionPerformed

    public void pathView(){
        try {
            int indexOrd = getIndexOrd();
            pFrom = orddao.getFrom(indexOrd);
            pTo = orddao.getTo(indexOrd);
            path = orddao.getPath(indexOrd);
            String from = pFrom.getStorehouse().getName();
            String to = pTo.getStorehouse().getName();

            pathModel = new PathTableModel(path);
            
            
            jtfFrom.setText(from);
            jtfTo.setText(to);
            
            jTablePath.setModel(pathModel);
        } catch (Exception ex) {
            Logger.getLogger(logistFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void refreshOrderView(){
    
         try{
             List<Order> orders = orddao.getAllOrders();
             ordModel = new OrderTableModel(orders);
             jTableOrder.setModel(ordModel);
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
        }
           
    }
    
    public void refreshStateField(int indexOrd) throws SQLException{
        
        String state = orddao.getState(indexOrd);
        String store = orddao.getStoreOnMoment(indexOrd);
        jtfState.setText(state);
        jtfStore.setText(store);
    
    }
    
    public int[] getIndexesOfProd(int indexOrd){
    
        int count = jTableProdsOfOrder.getRowCount();
        int[] arr  = new int[count];
        for (int i = 0; i < count; i++){
            arr[i] = Integer.parseInt(jTableProdsOfOrder.getValueAt(i, 0).toString());
        }
        return arr;
    }
    
    
    
    public int getIndexOrd(){
        int row = jTableOrder.getSelectedRow();
        int indexOrder = Integer.parseInt(ordModel.getValueAt(row, 0).toString());           
        return indexOrder;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTablePath;
    private javax.swing.JTable jTableProdsOfOrder;
    private javax.swing.JButton jbtnChangePath;
    private javax.swing.JButton jbtnChangeStatus;
    private javax.swing.JButton jbtnTime;
    private javax.swing.JButton jbtnTransport;
    private javax.swing.JTabbedPane jtbStore;
    private javax.swing.JTextField jtfFrom;
    private javax.swing.JTextField jtfState;
    private javax.swing.JTextField jtfStore;
    private javax.swing.JTextField jtfTo;
    // End of variables declaration//GEN-END:variables
}
