/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cargo.ui;

import com.cargo.storage.dao.OrderDAO;
import com.cargo.storage.dao.ProductDAO;
import com.cargo.storage.dao.StorehouseDAO;
import com.cargo.storage.model.Location;
import com.cargo.storage.model.Order;
import com.cargo.storage.model.Path;
import com.cargo.storage.model.Point;
import com.cargo.storage.model.Product;
import com.cargo.storage.model.Products;
import com.cargo.storage.model.Storehouse;
import com.cargo.tablemodels.OrderTableModel;
import com.cargo.tablemodels.PathTableModel;
import com.cargo.tablemodels.ProductTableModel;
import com.cargo.tablemodels.ProductsOnOrderTableModel;
import com.cargo.tablemodels.ProductsOnStoreTableModel;
import com.cargo.tablemodels.StorehouseTableModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author yura
 */
public class responordFrame extends javax.swing.JFrame  {

   
    /**
     * Creates new form userFrame
     */
    StorehouseTableModel model;
    ProductsOnStoreTableModel prodModel;
    ProductsOnOrderTableModel prodordModel;
    ProductTableModel productCatalog;
    PathTableModel pathModel;
    OrderTableModel ordModel;
    StorehouseDAO strhdao;
    OrderDAO orddao;
    ProductDAO proddao;
    List<Product> productsCatalog;
    Point pFrom;
    Point pTo;
    List<Path> path;
    int indexOrd;
    
    public static String password = "123";
    
    public responordFrame() throws Exception {
        
        List<Storehouse> storehouses = null;
        List<Order> orders = null;
        
        proddao = new ProductDAO();
        productsCatalog = proddao.listOfProduct();
        
        strhdao = new StorehouseDAO();
        storehouses = strhdao.getAllStorehouses();        
        orddao = new OrderDAO();        
        orders = orddao.getAllOrders();
        
        this.ordModel = new OrderTableModel(orders);
	this.model = new StorehouseTableModel(storehouses);
        this.productCatalog = new ProductTableModel(productsCatalog);
        
        initComponents();
        
    }

    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbStore = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProdsOfOrder = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtfFrom = new javax.swing.JTextField();
        jtfTo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtnOrder = new javax.swing.JButton();
        jbtnAddProd = new javax.swing.JButton();
        jbtnDelProd = new javax.swing.JButton();
        jbtnDel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtbStore.setName(" "); // NOI18N

        jScrollPane4.setViewportView(jTableProdsOfOrder);

        jLabel5.setText("Состав заказа:");

        jTableOrder.setModel(ordModel);
        jScrollPane3.setViewportView(jTableOrder);

        jTableOrder.getSelectionModel().addListSelectionListener( new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try{
                    int row = jTableOrder.getSelectedRow();
                    indexOrd = Integer.parseInt(ordModel.getValueAt(row, 0).toString());
                    //System.out.println(row);
                    List<Products> productsOfOrder = null;

                    productsOfOrder = orddao.getProductsOfOrder(indexOrd);

                    pFrom = orddao.getFrom(indexOrd);
                    pTo = orddao.getTo(indexOrd);
                    path = orddao.getPath(indexOrd);
                    String from = pFrom.getStorehouse().getName();
                    String to = pTo.getStorehouse().getName();

                    pathModel = new PathTableModel(path);

                    prodordModel = new ProductsOnOrderTableModel(productsOfOrder);
                    jtfFrom.setText(from);
                    jtfTo.setText(to);

                    jTableProdsOfOrder.setModel(prodordModel);

                } catch(Exception e){}

            }

        } );

        jLabel4.setText("Заказы:");

        jtfFrom.setEditable(false);
        jtfFrom.setText(" ");

        jtfTo.setEditable(false);
        jtfTo.setText(" ");

        jLabel9.setText("Откуда:");

        jLabel10.setText("Куда:");

        jbtnOrder.setText("Добавить заказ");
        jbtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrderActionPerformed(evt);
            }
        });

        jbtnAddProd.setText("Добавить продукт");
        jbtnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddProdActionPerformed(evt);
            }
        });

        jbtnDelProd.setText("Убрать из заказа");

        jbtnDel.setText("Удалить заказ");
        jbtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(169, 169, 169)
                        .addComponent(jbtnDel)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnOrder))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jtfTo)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDelProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAddProd))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 342, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtnOrder)
                                .addComponent(jbtnDel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtnAddProd)
                                .addComponent(jbtnDelProd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jtbStore.addTab("Заказы", jPanel2);

        jMenu1.setText("Файл");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Смена");

        jMenuItem1.setText("Смена пользователя");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbStore)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbStore)
                .addContainerGap())
        );

        jtbStore.getAccessibleContext().setAccessibleName("tabStore");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            strhdao.closeConnection();
            orddao.closeConnection();
            proddao.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(responordFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jbtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrderActionPerformed
         AddOrder addOrd = new AddOrder(this);
         addOrd.setVisible(true);
    }//GEN-LAST:event_jbtnOrderActionPerformed

    private void jbtnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddProdActionPerformed
        try {
            int indexStore = orddao.getFrom(indexOrd).getStorehouse().getId();
            AddProdToOrder apto = new AddProdToOrder(this,indexStore, indexOrd);
            apto.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(responordFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAddProdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            
        try {
            this.dispose();
            orddao.closeConnection();
            strhdao.closeConnection();
            proddao.closeConnection();
            
            Authorization auth = new Authorization(this, true);
            auth.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(responordFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDelActionPerformed
        try {
            orddao.deleteOrder(indexOrd);
            refreshOrderView();
        } catch (SQLException ex) {
            Logger.getLogger(responordFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Выберите заказ: " + ex, "Выберите заказ",
                                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnDelActionPerformed

  
    public void refreshOrderView() {
        try{
             List<Order> orders = orddao.getAllOrders();
             ordModel = new OrderTableModel(orders);
             jTableOrder.setModel(ordModel);
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
        }
    
    }
    
    public void refreshFromToView() {
        try{
        
            
        
        }
        catch(Exception exc){
        
        }
    
    }
    
    public void refreshProdsOfOrderView(int idOrd) {
        
       
            try{
                                       
                    List<Products> productsOnOrder = null;
                    productsOnOrder = orddao.getProductsOfOrder(idOrd);               
                    prodordModel = new ProductsOnOrderTableModel(productsOnOrder);                         
                    jTableProdsOfOrder.setModel(prodordModel);
                                                            
                }
            catch(Exception exc){
                JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
            
            }
            
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTableProdsOfOrder;
    private javax.swing.JButton jbtnAddProd;
    private javax.swing.JButton jbtnDel;
    private javax.swing.JButton jbtnDelProd;
    private javax.swing.JButton jbtnOrder;
    private javax.swing.JTabbedPane jtbStore;
    private javax.swing.JTextField jtfFrom;
    private javax.swing.JTextField jtfTo;
    // End of variables declaration//GEN-END:variables
}
