/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cargo.ui;

import com.cargo.storage.dao.OrderDAO;
import com.cargo.storage.dao.ProductDAO;
import com.cargo.storage.dao.StorehouseDAO;
import com.cargo.storage.model.Location;
import com.cargo.storage.model.Order;
import com.cargo.storage.model.Path;
import com.cargo.storage.model.Point;
import com.cargo.storage.model.Product;
import com.cargo.storage.model.Products;
import com.cargo.storage.model.Storehouse;
import com.cargo.tablemodels.OrderTableModel;
import com.cargo.tablemodels.PathTableModel;
import com.cargo.tablemodels.ProductTableModel;
import com.cargo.tablemodels.ProductsOnOrderTableModel;
import com.cargo.tablemodels.ProductsOnStoreTableModel;
import com.cargo.tablemodels.StorehouseTableModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yura
 */
public class userFrame extends javax.swing.JFrame {

    
    StorehouseTableModel model;
    ProductsOnStoreTableModel prodModel;
    ProductsOnOrderTableModel prodordModel;
    ProductTableModel productCatalog;
    PathTableModel pathModel;
    OrderTableModel ordModel;
    StorehouseDAO strhdao;
    OrderDAO orddao;
    ProductDAO proddao;
    List<Product> productsCatalog;
    Point pFrom;
    Point pTo;
    public static String password = "12345";
    
    public userFrame() throws Exception {
        
        List<Storehouse> storehouses = null;
        List<Order> orders = null;
        
        proddao = new ProductDAO();
        productsCatalog = proddao.listOfProduct();
        
        strhdao = new StorehouseDAO();
        storehouses = strhdao.getAllStorehouses();        
        orddao = new OrderDAO();        
        orders = orddao.getAllOrders();
        
        
        this.ordModel = new OrderTableModel(orders);
	this.model = new StorehouseTableModel(storehouses);
        this.productCatalog = new ProductTableModel(productsCatalog);
        
        initComponents();
        
    }

    
    public void refreshProductView(){
    
        try{
            productsCatalog = proddao.listOfProduct();
            productCatalog = new ProductTableModel(productsCatalog);
            jTableProduct.setModel(productCatalog);
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbStore = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStore = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdOnStore = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCity = new javax.swing.JLabel();
        jRegion = new javax.swing.JLabel();
        jCountry = new javax.swing.JLabel();
        jAddress = new javax.swing.JLabel();
        jPhone = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jbtnSearch = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnDel = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProdsOfOrder = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfState = new javax.swing.JTextField();
        jtfStore = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfFrom = new javax.swing.JTextField();
        jtfTo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePath = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtbStore.setName(" "); // NOI18N

        jTableStore.setAutoCreateRowSorter(true);
        jTableStore.setModel(model);
        jScrollPane1.setViewportView(jTableStore);

        jTableStore.getSelectionModel().addListSelectionListener( new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try{
                    int row = jTableStore.getSelectedRow();
                    int index = Integer.parseInt(model.getValueAt(row, 0).toString());
                    //System.out.println(row);
                    List<Products> productsOnStore = null;
                    Location locationOfStore = null;
                    productsOnStore = strhdao.getAllProductsOnStore(index);
                    locationOfStore = strhdao.getLocationForStore(index);

                    prodModel = new ProductsOnStoreTableModel(productsOnStore);

                    jCity.setText("Город:   " + locationOfStore.getCity());
                    jRegion.setText("Область:   " + locationOfStore.getRegion());
                    jCountry.setText("Страна:   " + locationOfStore.getCountry());
                    jAddress.setText("Адрес:   " + locationOfStore.getAddress());
                    jPhone.setText("Телефон:   " + locationOfStore.getPhone());

                    jTableProdOnStore.setModel(prodModel);
                } catch(Exception e){}

            }

        } );

        jScrollPane2.setViewportView(jTableProdOnStore);

        jLabel1.setText("Список продуктов на складе:");

        jLabel2.setText("Склады:");

        jLabel3.setText("Расположение склада:");

        jCity.setText(" ");

        jRegion.setText(" ");

        jCountry.setText(" ");

        jAddress.setText(" ");

        jPhone.setText(" ");

        jLabel8.setText("Каталог возможных продуктов");

        jtfSearch.setText(" ");

        jTableProduct.setModel(productCatalog);
        jScrollPane5.setViewportView(jTableProduct);

        jbtnSearch.setText("Поиск");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jbtnAdd.setText("Добавить");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnDel.setText("Удалить");
        jbtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDelActionPerformed(evt);
            }
        });

        jbtnUpdate.setText("Изменить");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnUpdate)
                .addContainerGap())
            .addComponent(jScrollPane5)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch)
                    .addComponent(jbtnAdd)
                    .addComponent(jbtnDel)
                    .addComponent(jbtnUpdate)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCity)
                            .addComponent(jRegion)
                            .addComponent(jCountry)
                            .addComponent(jAddress)
                            .addComponent(jPhone)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRegion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCountry)
                        .addGap(15, 15, 15)
                        .addComponent(jAddress)
                        .addGap(13, 13, 13)
                        .addComponent(jPhone)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtbStore.addTab("Склады", jPanel1);

        jScrollPane4.setViewportView(jTableProdsOfOrder);

        jLabel5.setText("Состав заказа:");

        jTableOrder.setModel(ordModel);
        jScrollPane3.setViewportView(jTableOrder);

        jTableOrder.getSelectionModel().addListSelectionListener( new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try{
                    int row = jTableOrder.getSelectedRow();
                    int indexOrd = Integer.parseInt(ordModel.getValueAt(row, 0).toString());
                    //System.out.println(row);
                    List<Products> productsOfOrder = null;
                    List<Path> path = null;
                    String state = "";
                    String store = "";
                    productsOfOrder = orddao.getProductsOfOrder(indexOrd);
                    state = orddao.getState(indexOrd);
                    store = orddao.getStoreOnMoment(indexOrd);
                    pFrom = orddao.getFrom(indexOrd);
                    pTo = orddao.getTo(indexOrd);
                    path = orddao.getPath(indexOrd);
                    String from = pFrom.getStorehouse().getName();
                    String to = pTo.getStorehouse().getName();

                    pathModel = new PathTableModel(path);
                    prodordModel = new ProductsOnOrderTableModel(productsOfOrder);
                    jtfFrom.setText(from);
                    jtfTo.setText(to);
                    jtfState.setText(state);
                    jtfStore.setText(store);
                    jTablePath.setModel(pathModel);
                    jTableProdsOfOrder.setModel(prodordModel);
                } catch(Exception e){}

            }

        } );

        jLabel4.setText("Заказы:");

        jLabel6.setText("Статус заказа:");

        jtfState.setEditable(false);
        jtfState.setText(" ");

        jtfStore.setEditable(false);
        jtfStore.setText(" ");

        jLabel7.setText("Склад:");

        jtfFrom.setEditable(false);
        jtfFrom.setText(" ");

        jtfTo.setEditable(false);
        jtfTo.setText(" ");

        jLabel9.setText("Откуда:");

        jLabel10.setText("Куда:");

        jLabel11.setText("Путь перемещения:");

        jScrollPane6.setViewportView(jTablePath);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfStore, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                    .addComponent(jtfState)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jtfTo)))
                    .addComponent(jLabel11))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbStore.addTab("Заказы", jPanel2);

        jMenu1.setText("Файл");

        jMenuSave.setText("Сохранить отчет");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Смена");

        jMenuItem1.setText("Смена пользователя");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbStore)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbStore)
                .addContainerGap())
        );

        jtbStore.getAccessibleContext().setAccessibleName("tabStore");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            strhdao.closeConnection();
            orddao.closeConnection();
            proddao.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(userFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            AddProduct ap = new AddProduct(userFrame.this);
            ap.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(userFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDelActionPerformed
            int row = jTableProduct.getSelectedRow();
            int index = Integer.parseInt(productCatalog.getValueAt(row, 0).toString());
            try{
                proddao.deleteProduct(index);
                refreshProductView();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ошибка: Вы не можете удалить"
                        + "продукт из каталога, так как он используется." , "Ошибка",
					JOptionPane.ERROR_MESSAGE);
        }
            
            
    }//GEN-LAST:event_jbtnDelActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        String searchName = jtfSearch.getText();
        try{
            List<Product> productList = null;

            if (searchName != null && searchName.trim().length() > 0) {
                    productList = proddao.searchProduct(searchName);
            } else {
                    productList = proddao.listOfProduct();
            }
            productCatalog = new ProductTableModel(productList);
            jTableProduct.setModel(productCatalog);
        } catch(SQLException exc){
            JOptionPane.showMessageDialog(this, "Возникла ошибка, связанная с каталогом" , "Ошибка",
					JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            this.dispose();
            orddao.closeConnection();
            strhdao.closeConnection();
            proddao.closeConnection();
            
            Authorization auth = new Authorization(this, true);
            auth.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(userFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        FinishOrders fcho = new FinishOrders();
        fcho.setVisible(true);
    }//GEN-LAST:event_jMenuSaveActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddress;
    private javax.swing.JLabel jCity;
    private javax.swing.JLabel jCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPhone;
    private javax.swing.JLabel jRegion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTablePath;
    private javax.swing.JTable jTableProdOnStore;
    private javax.swing.JTable jTableProdsOfOrder;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTable jTableStore;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDel;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTabbedPane jtbStore;
    private javax.swing.JTextField jtfFrom;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfState;
    private javax.swing.JTextField jtfStore;
    private javax.swing.JTextField jtfTo;
    // End of variables declaration//GEN-END:variables
}
